version: "3.8"

services:
  mariadb:
    image: mariadb:11
    container_name: reassurance-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: reassurance_back
      MARIADB_USER: reassurance
      MARIADB_PASSWORD: reassurance
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
